
package professor.swing;

import conexaodb.RequisicaoHttp;
import entidades.atividade.Atividade;
import entidades.turma.Turma;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class ProfessorSwing extends javax.swing.JFrame {

    ArrayList<Turma> turmas;
    ArrayList<Atividade> atividadesAndamento;
    ArrayList<Atividade> atividadesConcluidas;
    ArrayList<String> idTurmas;
    
    public ProfessorSwing() {
        initComponents();
        
        atividadesAndamento = new ArrayList<>();
        atividadesConcluidas = new ArrayList<>();
        
        setSize(934, 565);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFundo = new javax.swing.JTabbedPane();
        jPHome = new javax.swing.JPanel();
        jLbCodTurma = new javax.swing.JLabel();
        jLbPontuacaoTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLbQntAlunosTurma = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jListaTurmas = new javax.swing.JList<>();
        jSeparator8 = new javax.swing.JSeparator();
        jTFPesquisar = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLbNomeTurma = new javax.swing.JLabel();
        jLbColocacaoRankingTurma = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLbPontuacaoTotal1 = new javax.swing.JLabel();
        jLbPontuacaoTotalTurma = new javax.swing.JLabel();
        jLbImagemTurma = new javax.swing.JLabel();
        jLbCursoTurma = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPAtividades = new javax.swing.JPanel();
        jTBFundo = new javax.swing.JTabbedPane();
        jPEmAndamento = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListaAtividadesAndamento = new javax.swing.JList<>();
        jTFPesquisarEmAndamento = new javax.swing.JTextField();
        imagemLupa = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLbNomeAtividadeEmAndamento = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTADescricaoEmAndamento = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLbPontuacaoTerceiro = new javax.swing.JLabel();
        jLbPontuacaoPrimeiro = new javax.swing.JLabel();
        jLbPontuacaoSegundo = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLbLocalEmAndamento = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        jLbDataEmAndamento = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLbHoraEmAndamento = new javax.swing.JLabel();
        jBEditar = new javax.swing.JButton();
        jPConcluidas = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jTFPesquisarConcluidas = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListaAtividadesConcluidas = new javax.swing.JList<>();
        jSeparator5 = new javax.swing.JSeparator();
        jLbNomeAtividadeConcluida = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTADescricaoConcluidas = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLbTurmaPrimeiroLugar = new javax.swing.JLabel();
        jLbTurmaSegundoLugar = new javax.swing.JLabel();
        jLbTurmaTerceiroLugar = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLbDataConcluidas = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLbHoraConcluidas = new javax.swing.JLabel();
        jLbLocalConcluidas = new javax.swing.JLabel();
        jPRanking = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTRanking = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(934, 565));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTFundo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jPHome.setBackground(new java.awt.Color(254, 254, 254));
        jPHome.setToolTipText("");
        jPHome.setLayout(null);

        jLbCodTurma.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLbCodTurma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbCodTurma.setText("INF4AM");
        jLbCodTurma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPHome.add(jLbCodTurma);
        jLbCodTurma.setBounds(220, 10, 700, 16);

        jLbPontuacaoTotal.setText("lugar");
        jPHome.add(jLbPontuacaoTotal);
        jLbPontuacaoTotal.setBounds(560, 130, 50, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/school.png"))); // NOI18N
        jLabel7.setText("Curso:");
        jPHome.add(jLabel7);
        jLabel7.setBounds(280, 230, 90, 17);
        jPHome.add(jSeparator1);
        jSeparator1.setBounds(220, 340, 720, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/emoticon-cool.png"))); // NOI18N
        jLabel11.setText("Quantidade de alunos: ");
        jPHome.add(jLabel11);
        jLabel11.setBounds(280, 260, 200, 17);

        jLbQntAlunosTurma.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbQntAlunosTurma.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLbQntAlunosTurma.setText("34");
        jPHome.add(jLbQntAlunosTurma);
        jLbQntAlunosTurma.setBounds(550, 260, 40, 20);

        jListaTurmas.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jListaTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaTurmasMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jListaTurmas);

        jPHome.add(jScrollPane10);
        jScrollPane10.setBounds(0, 60, 210, 450);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPHome.add(jSeparator8);
        jSeparator8.setBounds(210, 0, 20, 500);

        jTFPesquisar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTFPesquisar.setText("Pesquisar");
        jTFPesquisar.setPreferredSize(new java.awt.Dimension(92, 27));
        jTFPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPesquisarActionPerformed(evt);
            }
        });
        jPHome.add(jTFPesquisar);
        jTFPesquisar.setBounds(40, 10, 170, 27);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/magnify.png"))); // NOI18N
        jPHome.add(jLabel57);
        jLabel57.setBounds(10, 10, 0, 0);

        jLbNomeTurma.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLbNomeTurma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNomeTurma.setText("INF Laranja");
        jPHome.add(jLbNomeTurma);
        jLbNomeTurma.setBounds(220, 30, 700, 30);

        jLbColocacaoRankingTurma.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbColocacaoRankingTurma.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLbColocacaoRankingTurma.setText("1° ");
        jPHome.add(jLbColocacaoRankingTurma);
        jLbColocacaoRankingTurma.setBounds(470, 130, 70, 30);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trending-up.png"))); // NOI18N
        jLabel59.setText("Pontuação total: ");
        jPHome.add(jLabel59);
        jLabel59.setBounds(280, 100, 150, 17);

        jLbPontuacaoTotal1.setText("pontos");
        jPHome.add(jLbPontuacaoTotal1);
        jLbPontuacaoTotal1.setBounds(560, 100, 50, 20);

        jLbPontuacaoTotalTurma.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoTotalTurma.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLbPontuacaoTotalTurma.setText("2000");
        jPHome.add(jLbPontuacaoTotalTurma);
        jLbPontuacaoTotalTurma.setBounds(430, 100, 110, 21);

        jLbImagemTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/22473670.png"))); // NOI18N
        jPHome.add(jLbImagemTurma);
        jLbImagemTurma.setBounds(750, 10, 150, 0);

        jLbCursoTurma.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbCursoTurma.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLbCursoTurma.setText("Informática");
        jPHome.add(jLbCursoTurma);
        jLbCursoTurma.setBounds(490, 230, 100, 20);
        jPHome.add(jSeparator9);
        jSeparator9.setBounds(210, 180, 720, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trophy-variant.png"))); // NOI18N
        jLabel6.setText("Colocação no Ranking: ");
        jPHome.add(jLabel6);
        jLabel6.setBounds(280, 130, 158, 30);

        jTFundo.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/home.png")), jPHome); // NOI18N

        jPAtividades.setBackground(new java.awt.Color(255, 254, 254));
        jPAtividades.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jTBFundo.setBackground(new java.awt.Color(254, 254, 254));
        jTBFundo.setForeground(new java.awt.Color(1, 1, 1));
        jTBFundo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jPEmAndamento.setBackground(new java.awt.Color(255, 252, 250));
        jPEmAndamento.setLayout(null);

        jListaAtividadesAndamento.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jListaAtividadesAndamento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Atividade 6", "Atividade 7", "Atividade 8", "Atividade 9", "Atividade 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListaAtividadesAndamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaAtividadesAndamentoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListaAtividadesAndamento);

        jPEmAndamento.add(jScrollPane3);
        jScrollPane3.setBounds(0, 60, 210, 410);

        jTFPesquisarEmAndamento.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTFPesquisarEmAndamento.setText("Pesquisar");
        jTFPesquisarEmAndamento.setPreferredSize(new java.awt.Dimension(92, 27));
        jTFPesquisarEmAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPesquisarEmAndamentoActionPerformed(evt);
            }
        });
        jPEmAndamento.add(jTFPesquisarEmAndamento);
        jTFPesquisarEmAndamento.setBounds(40, 10, 170, 27);

        imagemLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/magnify.png"))); // NOI18N
        jPEmAndamento.add(imagemLupa);
        imagemLupa.setBounds(10, 10, 0, 0);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPEmAndamento.add(jSeparator2);
        jSeparator2.setBounds(210, 0, 20, 470);

        jLbNomeAtividadeEmAndamento.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLbNomeAtividadeEmAndamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNomeAtividadeEmAndamento.setText("Atividade 6");
        jPEmAndamento.add(jLbNomeAtividadeEmAndamento);
        jLbNomeAtividadeEmAndamento.setBounds(220, 20, 690, 28);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/map-marker.png"))); // NOI18N
        jLabel19.setText("Local: ");
        jPEmAndamento.add(jLabel19);
        jLabel19.setBounds(240, 420, 90, 20);

        jTADescricaoEmAndamento.setEditable(false);
        jTADescricaoEmAndamento.setColumns(20);
        jTADescricaoEmAndamento.setRows(5);
        jScrollPane7.setViewportView(jTADescricaoEmAndamento);

        jPEmAndamento.add(jScrollPane7);
        jScrollPane7.setBounds(240, 100, 640, 120);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/format-align-left.png"))); // NOI18N
        jLabel20.setText("Descrição:");
        jPEmAndamento.add(jLabel20);
        jLabel20.setBounds(240, 70, 73, 17);
        jPEmAndamento.add(jSeparator3);
        jSeparator3.setBounds(430, 50, 270, 20);

        jLabel21.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel21.setText("3° lugar");
        jPEmAndamento.add(jLabel21);
        jLabel21.setBounds(360, 300, 60, 18);

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel22.setText("1° lugar");
        jPEmAndamento.add(jLabel22);
        jLabel22.setBounds(360, 260, 60, 18);

        jLabel44.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel44.setText("2° lugar");
        jPEmAndamento.add(jLabel44);
        jLabel44.setBounds(360, 280, 60, 18);

        jLabel45.setText("pontos");
        jPEmAndamento.add(jLabel45);
        jLabel45.setBounds(530, 300, 49, 17);

        jLabel46.setText("pontos");
        jPEmAndamento.add(jLabel46);
        jLabel46.setBounds(530, 260, 49, 17);

        jLabel47.setText("pontos");
        jPEmAndamento.add(jLabel47);
        jLabel47.setBounds(530, 280, 49, 17);

        jLbPontuacaoTerceiro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoTerceiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbPontuacaoTerceiro.setText("100");
        jPEmAndamento.add(jLbPontuacaoTerceiro);
        jLbPontuacaoTerceiro.setBounds(420, 300, 110, 17);

        jLbPontuacaoPrimeiro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoPrimeiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbPontuacaoPrimeiro.setText("300");
        jPEmAndamento.add(jLbPontuacaoPrimeiro);
        jLbPontuacaoPrimeiro.setBounds(420, 260, 110, 17);

        jLbPontuacaoSegundo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoSegundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbPontuacaoSegundo.setText("200");
        jPEmAndamento.add(jLbPontuacaoSegundo);
        jLbPontuacaoSegundo.setBounds(420, 280, 110, 17);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trophy-variant.png"))); // NOI18N
        jLabel51.setText("Pontuação: ");
        jPEmAndamento.add(jLabel51);
        jLabel51.setBounds(240, 230, 82, 17);

        jLbLocalEmAndamento.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbLocalEmAndamento.setText("Parque do Chimirrão");
        jPEmAndamento.add(jLbLocalEmAndamento);
        jLbLocalEmAndamento.setBounds(360, 420, 160, 21);
        jPEmAndamento.add(jSeparator4);
        jSeparator4.setBounds(210, 330, 710, 20);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/calendar-check.png"))); // NOI18N
        jLabel53.setText("Data: ");
        jPEmAndamento.add(jLabel53);
        jLabel53.setBounds(240, 360, 90, 20);

        jLbDataEmAndamento.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbDataEmAndamento.setText("18 de novembro de 2016");
        jPEmAndamento.add(jLbDataEmAndamento);
        jLbDataEmAndamento.setBounds(360, 360, 197, 21);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/clock.png"))); // NOI18N
        jLabel55.setText("Hora: ");
        jPEmAndamento.add(jLabel55);
        jLabel55.setBounds(240, 390, 90, 20);

        jLbHoraEmAndamento.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbHoraEmAndamento.setText("8:30 h");
        jPEmAndamento.add(jLbHoraEmAndamento);
        jLbHoraEmAndamento.setBounds(360, 390, 48, 21);

        jBEditar.setBackground(new java.awt.Color(1, 1, 1));
        jBEditar.setForeground(new java.awt.Color(254, 254, 254));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/pencil.png"))); // NOI18N
        jBEditar.setText(" Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        jPEmAndamento.add(jBEditar);
        jBEditar.setBounds(740, 420, 150, 28);

        jTBFundo.addTab("Em andamento", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/update.png")), jPEmAndamento); // NOI18N

        jPConcluidas.setBackground(new java.awt.Color(254, 250, 247));
        jPConcluidas.setLayout(null);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/magnify.png"))); // NOI18N
        jPConcluidas.add(jLabel48);
        jLabel48.setBounds(10, 10, 0, 0);

        jTFPesquisarConcluidas.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTFPesquisarConcluidas.setText("Pesquisar");
        jTFPesquisarConcluidas.setPreferredSize(new java.awt.Dimension(92, 27));
        jTFPesquisarConcluidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPesquisarConcluidasActionPerformed(evt);
            }
        });
        jPConcluidas.add(jTFPesquisarConcluidas);
        jTFPesquisarConcluidas.setBounds(40, 10, 170, 27);

        jListaAtividadesConcluidas.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jListaAtividadesConcluidas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Atividade 6", "Atividade 7", "Atividade 8", "Atividade 9", "Atividade 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListaAtividadesConcluidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaAtividadesConcluidasMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jListaAtividadesConcluidas);

        jPConcluidas.add(jScrollPane8);
        jScrollPane8.setBounds(0, 60, 210, 410);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPConcluidas.add(jSeparator5);
        jSeparator5.setBounds(210, 0, 20, 470);

        jLbNomeAtividadeConcluida.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLbNomeAtividadeConcluida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNomeAtividadeConcluida.setText("Atividade 6");
        jPConcluidas.add(jLbNomeAtividadeConcluida);
        jLbNomeAtividadeConcluida.setBounds(220, 20, 690, 28);
        jPConcluidas.add(jSeparator6);
        jSeparator6.setBounds(430, 50, 270, 20);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/format-align-left.png"))); // NOI18N
        jLabel49.setText("Descrição:");
        jPConcluidas.add(jLabel49);
        jLabel49.setBounds(240, 70, 73, 17);

        jTADescricaoConcluidas.setEditable(false);
        jTADescricaoConcluidas.setColumns(20);
        jTADescricaoConcluidas.setRows(5);
        jScrollPane9.setViewportView(jTADescricaoConcluidas);

        jPConcluidas.add(jScrollPane9);
        jScrollPane9.setBounds(240, 100, 640, 120);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trophy-variant.png"))); // NOI18N
        jLabel52.setText("Vencedores:");
        jPConcluidas.add(jLabel52);
        jLabel52.setBounds(240, 230, 130, 17);

        jLabel50.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel50.setText("1° lugar");
        jPConcluidas.add(jLabel50);
        jLabel50.setBounds(360, 260, 60, 18);

        jLabel54.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel54.setText("2° lugar");
        jPConcluidas.add(jLabel54);
        jLabel54.setBounds(360, 280, 60, 18);

        jLabel56.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel56.setText("3° lugar");
        jPConcluidas.add(jLabel56);
        jLabel56.setBounds(360, 300, 60, 18);

        jLbTurmaPrimeiroLugar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbTurmaPrimeiroLugar.setText("INF4AM");
        jPConcluidas.add(jLbTurmaPrimeiroLugar);
        jLbTurmaPrimeiroLugar.setBounds(490, 260, 180, 17);

        jLbTurmaSegundoLugar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbTurmaSegundoLugar.setText("REFRI3AT");
        jPConcluidas.add(jLbTurmaSegundoLugar);
        jLbTurmaSegundoLugar.setBounds(490, 280, 180, 17);

        jLbTurmaTerceiroLugar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbTurmaTerceiroLugar.setText("INF1AT");
        jPConcluidas.add(jLbTurmaTerceiroLugar);
        jLbTurmaTerceiroLugar.setBounds(490, 300, 180, 17);
        jPConcluidas.add(jSeparator7);
        jSeparator7.setBounds(210, 330, 710, 20);

        jLbDataConcluidas.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbDataConcluidas.setText("18 de novembro de 2016");
        jPConcluidas.add(jLbDataConcluidas);
        jLbDataConcluidas.setBounds(360, 360, 197, 21);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/calendar-check.png"))); // NOI18N
        jLabel60.setText("Data: ");
        jPConcluidas.add(jLabel60);
        jLabel60.setBounds(240, 360, 90, 20);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/clock.png"))); // NOI18N
        jLabel61.setText("Hora: ");
        jPConcluidas.add(jLabel61);
        jLabel61.setBounds(240, 390, 90, 20);

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/map-marker.png"))); // NOI18N
        jLabel62.setText("Local: ");
        jPConcluidas.add(jLabel62);
        jLabel62.setBounds(240, 420, 90, 20);

        jLbHoraConcluidas.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbHoraConcluidas.setText("8:30 h");
        jPConcluidas.add(jLbHoraConcluidas);
        jLbHoraConcluidas.setBounds(360, 390, 48, 21);

        jLbLocalConcluidas.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbLocalConcluidas.setText("Parque do Chimirrão");
        jPConcluidas.add(jLbLocalConcluidas);
        jLbLocalConcluidas.setBounds(360, 420, 160, 21);

        jTBFundo.addTab("Concluídas", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/check-circle-outline.png")), jPConcluidas); // NOI18N

        javax.swing.GroupLayout jPAtividadesLayout = new javax.swing.GroupLayout(jPAtividades);
        jPAtividades.setLayout(jPAtividadesLayout);
        jPAtividadesLayout.setHorizontalGroup(
            jPAtividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTBFundo)
        );
        jPAtividadesLayout.setVerticalGroup(
            jPAtividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAtividadesLayout.createSequentialGroup()
                .addComponent(jTBFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTFundo.addTab("Atividades", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/tooltip-text.png")), jPAtividades); // NOI18N

        jPRanking.setBackground(new java.awt.Color(254, 254, 254));

        jTRanking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turma", "Pontuação total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTRanking.setEnabled(false);
        jTRanking.setGridColor(new java.awt.Color(254, 254, 254));
        jScrollPane1.setViewportView(jTRanking);
        if (jTRanking.getColumnModel().getColumnCount() > 0) {
            jTRanking.getColumnModel().getColumn(0).setResizable(false);
            jTRanking.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPRankingLayout = new javax.swing.GroupLayout(jPRanking);
        jPRanking.setLayout(jPRankingLayout);
        jPRankingLayout.setHorizontalGroup(
            jPRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPRankingLayout.setVerticalGroup(
            jPRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        jTFundo.addTab("Ranking", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trophy-variant.png")), jPRanking); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(254, 254, 254));

        jMenu2.setText("Atividades");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Nova atividade");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Turmas");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Cadastrar turma");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Opções");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Informações GamesApp");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setText("Alterar senha");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTFundo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 545, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new InformacoesSwing().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
       //Lista de turmas HOME
        DefaultListModel listaTurma = new DefaultListModel();
        try {
            /*for (int i = 0; i < 10; i++) {
            listaTurma.addElement("INF4AM: " + i);
            }*/
            turmas = new RequisicaoHttp().getTurmaTodas();
            idTurmas = new ArrayList<>();
            
            for (int i = 0; i < turmas.size(); i++) {
                listaTurma.addElement(turmas.get(i).getNome());
                idTurmas.add(turmas.get(i).getId());
            }
            
            for (int i = 0; i < idTurmas.size(); i++) {
                System.out.println("id: " + idTurmas.get(i));
            }
        
            jListaTurmas.setModel(listaTurma);
        } catch (Exception ex) {
            Logger.getLogger(ProfessorSwing.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Lista Atividades em andamento e lista atividades concluidas
        DefaultListModel listaAtividadesAndamento = new DefaultListModel();
        DefaultListModel listaAtividadesConcluidas = new DefaultListModel();
        try {
            ArrayList<Atividade> todasAtividades = new RequisicaoHttp().getAtividadeTodas();
            
            for (int i = 0; i < todasAtividades.size(); i++) {
                if (todasAtividades.get(i).getSituacao().equals("Em andamento")) {
                    atividadesAndamento.add(todasAtividades.get(i));
                } else {
                    atividadesConcluidas.add(todasAtividades.get(i));
                }
            }
            
            for (int i = 0; i < atividadesAndamento.size(); i++) {
                listaAtividadesAndamento.addElement(atividadesAndamento.get(i).getNome());
            }
            jListaAtividadesAndamento.setModel(listaAtividadesAndamento);
            
            for (int i = 0; i < atividadesConcluidas.size(); i++) {
                listaAtividadesConcluidas.addElement(atividadesConcluidas.get(i).getNome());
            }
            jListaAtividadesConcluidas.setModel(listaAtividadesConcluidas);
            
        } catch (Exception ex) {
            Logger.getLogger(ProfessorSwing.class.getName()).log(Level.SEVERE, null, ex);
        }
        //tabela do ranking
        DefaultTableModel model = (DefaultTableModel)jTRanking.getModel();
        model.setNumRows(0);
        //Fazer pesquisa no banco e retornar todas as turmas e sua pontuação em ordem decrescebte
        model.addRow(new Object[] {"INF4AM", "5000"});
      
    }//GEN-LAST:event_formWindowOpened

    private void jListaAtividadesConcluidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaAtividadesConcluidasMouseClicked
        
        //pegar as informaões do objeto selecionado
        int itemSelecionado = jListaAtividadesConcluidas.getSelectedIndex();
        //alterar as informações da tela CONCLUÍDAS
        jLbNomeAtividadeConcluida.setText(atividadesConcluidas.get(itemSelecionado).getNome());
        jTADescricaoConcluidas.setText(atividadesConcluidas.get(itemSelecionado).getDescricao());
        jLbDataConcluidas.setText(atividadesConcluidas.get(itemSelecionado).getData());
        jLbHoraConcluidas.setText(atividadesConcluidas.get(itemSelecionado).getHora());
        jLbLocalConcluidas.setText(atividadesConcluidas.get(itemSelecionado).getEndereco().toString());
        
        if (atividadesConcluidas.get(itemSelecionado).getClassificacao() != null) {
            jLbTurmaPrimeiroLugar.setText(atividadesConcluidas.get(itemSelecionado).getClassificacao().getPrimeiro());
            jLbTurmaSegundoLugar.setText(atividadesConcluidas.get(itemSelecionado).getClassificacao().getSegundo());
            jLbTurmaTerceiroLugar.setText(atividadesConcluidas.get(itemSelecionado).getClassificacao().getTerceiro()); 
        } else {
            jLbTurmaPrimeiroLugar.setText("Em apuração");
            jLbTurmaSegundoLugar.setText("Em apuração");
            jLbTurmaTerceiroLugar.setText("Em apuração"); 
        }
    }//GEN-LAST:event_jListaAtividadesConcluidasMouseClicked

    private void jTFPesquisarConcluidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPesquisarConcluidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesquisarConcluidasActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Pegar as informações da atividade e mandar pra tela nova atividade para editar");
        new NovaAtividadeSwing().setVisible(true);
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jTFPesquisarEmAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPesquisarEmAndamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesquisarEmAndamentoActionPerformed

    private void jListaAtividadesAndamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaAtividadesAndamentoMouseClicked

        //pegar as informaões do objeto selecionado
        int itemSelecionado = jListaAtividadesAndamento.getSelectedIndex();
        
        //alterar as informações da tela EM ANDAMENTO       
        jLbNomeAtividadeEmAndamento.setText(atividadesAndamento.get(itemSelecionado).getNome());
        jTADescricaoEmAndamento.setText(atividadesAndamento.get(itemSelecionado).getDescricao());
        jLbDataEmAndamento.setText(atividadesAndamento.get(itemSelecionado).getData());
        jLbHoraEmAndamento.setText(atividadesAndamento.get(itemSelecionado).getHora());
        jLbLocalEmAndamento.setText(atividadesAndamento.get(itemSelecionado).getEndereco().toString());
        jLbPontuacaoPrimeiro.setText(String.valueOf(atividadesAndamento.get(itemSelecionado).getPontuacao().getPrimeiro()));
        jLbPontuacaoSegundo.setText(String.valueOf(atividadesAndamento.get(itemSelecionado).getPontuacao().getSegundo()));
        jLbPontuacaoTerceiro.setText(String.valueOf(atividadesAndamento.get(itemSelecionado).getPontuacao().getTerceiro()));
    }//GEN-LAST:event_jListaAtividadesAndamentoMouseClicked

    private void jListaTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaTurmasMouseClicked
        
        //pegar informações do objeto (TURMA) selecionado

        int itemSelecionado = jListaTurmas.getSelectedIndex();
        //System.out.println("item: " + itemSelecionado);
        //alterar as informações da tela HOME
        jLbCodTurma.setText(turmas.get(itemSelecionado).getCurso() + " "
                + turmas.get(itemSelecionado).getAnoInicio());
        jLbNomeTurma.setText(turmas.get(itemSelecionado).getNome());
        jLbPontuacaoTotalTurma.setText(String.valueOf(turmas.get(itemSelecionado).getPontos()));
        jLbCursoTurma.setText(turmas.get(itemSelecionado).getCurso());
        jLbQntAlunosTurma.setText(String.valueOf(turmas.get(itemSelecionado).getAlunos().size()));
    }//GEN-LAST:event_jListaTurmasMouseClicked

    private void jTFPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesquisarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        new NovaAtividadeSwing().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        new NovaTurmaSwing().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        new AlterarSenhaSwing().setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagemLupa;
    private javax.swing.JButton jBEditar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLbCodTurma;
    private javax.swing.JLabel jLbColocacaoRankingTurma;
    private javax.swing.JLabel jLbCursoTurma;
    private javax.swing.JLabel jLbDataConcluidas;
    private javax.swing.JLabel jLbDataEmAndamento;
    private javax.swing.JLabel jLbHoraConcluidas;
    private javax.swing.JLabel jLbHoraEmAndamento;
    private javax.swing.JLabel jLbImagemTurma;
    private javax.swing.JLabel jLbLocalConcluidas;
    private javax.swing.JLabel jLbLocalEmAndamento;
    private javax.swing.JLabel jLbNomeAtividadeConcluida;
    private javax.swing.JLabel jLbNomeAtividadeEmAndamento;
    private javax.swing.JLabel jLbNomeTurma;
    private javax.swing.JLabel jLbPontuacaoPrimeiro;
    private javax.swing.JLabel jLbPontuacaoSegundo;
    private javax.swing.JLabel jLbPontuacaoTerceiro;
    private javax.swing.JLabel jLbPontuacaoTotal;
    private javax.swing.JLabel jLbPontuacaoTotal1;
    private javax.swing.JLabel jLbPontuacaoTotalTurma;
    private javax.swing.JLabel jLbQntAlunosTurma;
    private javax.swing.JLabel jLbTurmaPrimeiroLugar;
    private javax.swing.JLabel jLbTurmaSegundoLugar;
    private javax.swing.JLabel jLbTurmaTerceiroLugar;
    private javax.swing.JList<String> jListaAtividadesAndamento;
    private javax.swing.JList<String> jListaAtividadesConcluidas;
    private javax.swing.JList<String> jListaTurmas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPAtividades;
    private javax.swing.JPanel jPConcluidas;
    private javax.swing.JPanel jPEmAndamento;
    private javax.swing.JPanel jPHome;
    private javax.swing.JPanel jPRanking;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTADescricaoConcluidas;
    private javax.swing.JTextArea jTADescricaoEmAndamento;
    private javax.swing.JTabbedPane jTBFundo;
    private javax.swing.JTextField jTFPesquisar;
    private javax.swing.JTextField jTFPesquisarConcluidas;
    private javax.swing.JTextField jTFPesquisarEmAndamento;
    private javax.swing.JTabbedPane jTFundo;
    private javax.swing.JTable jTRanking;
    // End of variables declaration//GEN-END:variables
}
