/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package professor.swing;



public class ProfessorSwing extends javax.swing.JFrame {

    public ProfessorSwing() {
        initComponents();
        
        setSize(934, 565);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTRanking = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLbPontuacaoTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLbCorTurma = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLbQntAlunos = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jListaTurmas = new javax.swing.JList<>();
        jSeparator8 = new javax.swing.JSeparator();
        jTFPesquisar = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLbNomeTurma = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLbPontuacaoTotal1 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLbImagemTurma = new javax.swing.JLabel();
        jLbCurso = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTEmAndamento = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListaAtividadesAndamento = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLbNomeAtividade = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTADescricao = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLbPontuacaoTerceiro = new javax.swing.JLabel();
        jLbPontuacaoPrimeiro = new javax.swing.JLabel();
        jLbPontuacaoSegundo = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLbLocal = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        jLbData = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLbHora = new javax.swing.JLabel();
        jBEditar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jListaAtividadesAndamento1 = new javax.swing.JList<>();
        jSeparator5 = new javax.swing.JSeparator();
        jLbNomeAtividade1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTADescricao1 = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLbPontuacaoPrimeiro1 = new javax.swing.JLabel();
        jLbPontuacaoSegundo1 = new javax.swing.JLabel();
        jLbPontuacaoTerceiro1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLbData1 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLbHora1 = new javax.swing.JLabel();
        jLbLocal1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTRanking.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INF4AM");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 10, 700, 16);

        jLbPontuacaoTotal.setText("lugar");
        jPanel1.add(jLbPontuacaoTotal);
        jLbPontuacaoTotal.setBounds(560, 130, 50, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trophy-award.png"))); // NOI18N
        jLabel5.setText("Últimas atividades ganhas:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 370, 230, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/school.png"))); // NOI18N
        jLabel7.setText("Curso:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 220, 90, 24);

        jLbCorTurma.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbCorTurma.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLbCorTurma.setText("Laranja");
        jPanel1.add(jLbCorTurma);
        jLbCorTurma.setBounds(490, 250, 100, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/slack.png"))); // NOI18N
        jLabel9.setText("Cor da turma:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(280, 250, 130, 24);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(220, 340, 720, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/emoticon-cool.png"))); // NOI18N
        jLabel11.setText("Quantidade de alunos: ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 280, 200, 24);

        jLbQntAlunos.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbQntAlunos.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLbQntAlunos.setText("34");
        jPanel1.add(jLbQntAlunos);
        jLbQntAlunos.setBounds(550, 280, 40, 20);

        jListaTurmas.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jListaTurmas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "INF4AM", "REFRI4AM", "INF3AM", "REFRI3AM", "INF2AT", "INF2AM", "REFRI2AT", "REFRI2AT", "INF1AT", "INF1AM", "REFRI1AT", "REFRI1AM" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListaTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaTurmasMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jListaTurmas);

        jPanel1.add(jScrollPane10);
        jScrollPane10.setBounds(0, 60, 210, 450);

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(210, 0, 20, 500);

        jTFPesquisar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTFPesquisar.setText("Pesquisar");
        jTFPesquisar.setPreferredSize(new java.awt.Dimension(92, 27));
        jTFPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(jTFPesquisar);
        jTFPesquisar.setBounds(40, 10, 170, 27);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/magnify.png"))); // NOI18N
        jPanel1.add(jLabel57);
        jLabel57.setBounds(10, 10, 24, 24);

        jLbNomeTurma.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLbNomeTurma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNomeTurma.setText("INF Laranja");
        jPanel1.add(jLbNomeTurma);
        jLbNomeTurma.setBounds(220, 30, 700, 30);

        jLabel58.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel58.setText("1° ");
        jPanel1.add(jLabel58);
        jLabel58.setBounds(470, 130, 70, 30);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trending-up.png"))); // NOI18N
        jLabel59.setText("Pontuação total: ");
        jPanel1.add(jLabel59);
        jLabel59.setBounds(280, 100, 150, 17);

        jLbPontuacaoTotal1.setText("pontos");
        jPanel1.add(jLbPontuacaoTotal1);
        jLbPontuacaoTotal1.setBounds(560, 100, 50, 20);

        jLabel63.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel63.setText("2000");
        jPanel1.add(jLabel63);
        jLabel63.setBounds(430, 100, 110, 21);

        jLbImagemTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/22473670.png"))); // NOI18N
        jPanel1.add(jLbImagemTurma);
        jLbImagemTurma.setBounds(750, 10, 150, 152);

        jLbCurso.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbCurso.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLbCurso.setText("Informática");
        jPanel1.add(jLbCurso);
        jLbCurso.setBounds(490, 220, 100, 20);
        jPanel1.add(jSeparator9);
        jSeparator9.setBounds(210, 180, 720, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trophy-variant.png"))); // NOI18N
        jLabel6.setText("Colocação no Ranking: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(280, 130, 186, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/star-outline (1).png"))); // NOI18N
        jLabel2.setText("Aqui vai o nome da última atividade que aturma ganhou");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 450, 400, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/star-outline (1).png"))); // NOI18N
        jLabel3.setText("Aqui vai o nome da última atividade que aturma ganhou");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 407, 400, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/star-outline (1).png"))); // NOI18N
        jLabel4.setText("Aqui vai o nome da última atividade que aturma ganhou");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 430, 400, 20);

        jTRanking.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/home.png")), jPanel1); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 254, 254));
        jPanel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jTEmAndamento.setBackground(new java.awt.Color(254, 254, 254));
        jTEmAndamento.setForeground(new java.awt.Color(1, 1, 1));
        jTEmAndamento.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 252, 250));
        jPanel5.setLayout(null);

        jListaAtividadesAndamento.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jListaAtividadesAndamento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Atividade 6", "Atividade 7", "Atividade 8", "Atividade 9", "Atividade 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListaAtividadesAndamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaAtividadesAndamentoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListaAtividadesAndamento);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(0, 60, 210, 410);

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTextField1.setText("Pesquisar");
        jTextField1.setPreferredSize(new java.awt.Dimension(92, 27));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1);
        jTextField1.setBounds(40, 10, 170, 27);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/magnify.png"))); // NOI18N
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 10, 24, 24);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator2);
        jSeparator2.setBounds(210, 0, 20, 470);

        jLbNomeAtividade.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLbNomeAtividade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNomeAtividade.setText("Atividade 6");
        jPanel5.add(jLbNomeAtividade);
        jLbNomeAtividade.setBounds(220, 20, 690, 28);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/map-marker.png"))); // NOI18N
        jLabel19.setText("Local: ");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(240, 420, 90, 20);

        jTADescricao.setColumns(20);
        jTADescricao.setRows(5);
        jScrollPane7.setViewportView(jTADescricao);

        jPanel5.add(jScrollPane7);
        jScrollPane7.setBounds(240, 100, 640, 120);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/format-align-left.png"))); // NOI18N
        jLabel20.setText("Descrição:");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(240, 70, 101, 24);
        jPanel5.add(jSeparator3);
        jSeparator3.setBounds(430, 50, 270, 20);

        jLabel21.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel21.setText("3° lugar");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(360, 300, 60, 18);

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel22.setText("1° lugar");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(360, 260, 60, 18);

        jLabel44.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel44.setText("2° lugar");
        jPanel5.add(jLabel44);
        jLabel44.setBounds(360, 280, 60, 18);

        jLabel45.setText("pontos");
        jPanel5.add(jLabel45);
        jLabel45.setBounds(530, 300, 49, 17);

        jLabel46.setText("pontos");
        jPanel5.add(jLabel46);
        jLabel46.setBounds(530, 260, 49, 17);

        jLabel47.setText("pontos");
        jPanel5.add(jLabel47);
        jLabel47.setBounds(530, 280, 49, 17);

        jLbPontuacaoTerceiro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoTerceiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbPontuacaoTerceiro.setText("100");
        jPanel5.add(jLbPontuacaoTerceiro);
        jLbPontuacaoTerceiro.setBounds(420, 300, 110, 17);

        jLbPontuacaoPrimeiro.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoPrimeiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbPontuacaoPrimeiro.setText("300");
        jPanel5.add(jLbPontuacaoPrimeiro);
        jLbPontuacaoPrimeiro.setBounds(420, 260, 110, 17);

        jLbPontuacaoSegundo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoSegundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbPontuacaoSegundo.setText("200");
        jPanel5.add(jLbPontuacaoSegundo);
        jLbPontuacaoSegundo.setBounds(420, 280, 110, 17);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trophy-variant.png"))); // NOI18N
        jLabel51.setText("Pontuação: ");
        jPanel5.add(jLabel51);
        jLabel51.setBounds(240, 230, 110, 24);

        jLbLocal.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbLocal.setText("Parque do Chimirrão");
        jPanel5.add(jLbLocal);
        jLbLocal.setBounds(360, 420, 160, 21);
        jPanel5.add(jSeparator4);
        jSeparator4.setBounds(210, 330, 710, 20);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/calendar-check.png"))); // NOI18N
        jLabel53.setText("Data: ");
        jPanel5.add(jLabel53);
        jLabel53.setBounds(240, 360, 90, 20);

        jLbData.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbData.setText("18 de novembro de 2016");
        jPanel5.add(jLbData);
        jLbData.setBounds(360, 360, 197, 21);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/clock.png"))); // NOI18N
        jLabel55.setText("Hora: ");
        jPanel5.add(jLabel55);
        jLabel55.setBounds(240, 390, 90, 20);

        jLbHora.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbHora.setText("8:30 h");
        jPanel5.add(jLbHora);
        jLbHora.setBounds(360, 390, 48, 21);

        jBEditar.setBackground(new java.awt.Color(1, 1, 1));
        jBEditar.setForeground(new java.awt.Color(254, 254, 254));
        jBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/pencil.png"))); // NOI18N
        jBEditar.setText(" Editar");
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        jPanel5.add(jBEditar);
        jBEditar.setBounds(740, 420, 150, 30);

        jTEmAndamento.addTab("Em andamento", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/update.png")), jPanel5); // NOI18N

        jPanel6.setBackground(new java.awt.Color(254, 250, 247));
        jPanel6.setLayout(null);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/magnify.png"))); // NOI18N
        jPanel6.add(jLabel48);
        jLabel48.setBounds(10, 10, 24, 24);

        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTextField2.setText("Pesquisar");
        jTextField2.setPreferredSize(new java.awt.Dimension(92, 27));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField2);
        jTextField2.setBounds(40, 10, 170, 27);

        jListaAtividadesAndamento1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jListaAtividadesAndamento1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Atividade 6", "Atividade 7", "Atividade 8", "Atividade 9", "Atividade 10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListaAtividadesAndamento1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaAtividadesAndamento1MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jListaAtividadesAndamento1);

        jPanel6.add(jScrollPane8);
        jScrollPane8.setBounds(0, 60, 210, 410);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel6.add(jSeparator5);
        jSeparator5.setBounds(210, 0, 20, 470);

        jLbNomeAtividade1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLbNomeAtividade1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNomeAtividade1.setText("Atividade 6");
        jPanel6.add(jLbNomeAtividade1);
        jLbNomeAtividade1.setBounds(220, 20, 690, 28);
        jPanel6.add(jSeparator6);
        jSeparator6.setBounds(430, 50, 270, 20);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/format-align-left.png"))); // NOI18N
        jLabel49.setText("Descrição:");
        jPanel6.add(jLabel49);
        jLabel49.setBounds(240, 70, 101, 24);

        jTADescricao1.setColumns(20);
        jTADescricao1.setRows(5);
        jScrollPane9.setViewportView(jTADescricao1);

        jPanel6.add(jScrollPane9);
        jScrollPane9.setBounds(240, 100, 640, 120);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trophy-variant.png"))); // NOI18N
        jLabel52.setText("Vencedores:");
        jPanel6.add(jLabel52);
        jLabel52.setBounds(240, 230, 130, 24);

        jLabel50.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel50.setText("1° lugar");
        jPanel6.add(jLabel50);
        jLabel50.setBounds(360, 260, 60, 18);

        jLabel54.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel54.setText("2° lugar");
        jPanel6.add(jLabel54);
        jLabel54.setBounds(360, 280, 60, 18);

        jLabel56.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel56.setText("3° lugar");
        jPanel6.add(jLabel56);
        jLabel56.setBounds(360, 300, 60, 18);

        jLbPontuacaoPrimeiro1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoPrimeiro1.setText("INF4AM");
        jPanel6.add(jLbPontuacaoPrimeiro1);
        jLbPontuacaoPrimeiro1.setBounds(490, 260, 180, 17);

        jLbPontuacaoSegundo1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoSegundo1.setText("REFRI3AT");
        jPanel6.add(jLbPontuacaoSegundo1);
        jLbPontuacaoSegundo1.setBounds(490, 280, 180, 17);

        jLbPontuacaoTerceiro1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLbPontuacaoTerceiro1.setText("INF1AT");
        jPanel6.add(jLbPontuacaoTerceiro1);
        jLbPontuacaoTerceiro1.setBounds(490, 300, 180, 17);
        jPanel6.add(jSeparator7);
        jSeparator7.setBounds(210, 330, 710, 20);

        jLbData1.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbData1.setText("18 de novembro de 2016");
        jPanel6.add(jLbData1);
        jLbData1.setBounds(360, 360, 197, 21);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/calendar-check.png"))); // NOI18N
        jLabel60.setText("Data: ");
        jPanel6.add(jLabel60);
        jLabel60.setBounds(240, 360, 90, 20);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/clock.png"))); // NOI18N
        jLabel61.setText("Hora: ");
        jPanel6.add(jLabel61);
        jLabel61.setBounds(240, 390, 90, 20);

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/map-marker.png"))); // NOI18N
        jLabel62.setText("Local: ");
        jPanel6.add(jLabel62);
        jLabel62.setBounds(240, 420, 90, 20);

        jLbHora1.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbHora1.setText("8:30 h");
        jPanel6.add(jLbHora1);
        jLbHora1.setBounds(360, 390, 48, 21);

        jLbLocal1.setFont(new java.awt.Font("Ubuntu", 0, 17)); // NOI18N
        jLbLocal1.setText("Parque do Chimirrão");
        jPanel6.add(jLbLocal1);
        jLbLocal1.setBounds(360, 420, 160, 21);

        jTEmAndamento.addTab("Concluídas", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/check-circle-outline.png")), jPanel6); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTEmAndamento)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTEmAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTRanking.addTab("Atividades", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/tooltip-text.png")), jPanel4); // NOI18N

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        jTRanking.addTab("Ranking", new javax.swing.ImageIcon(getClass().getResource("/imagens/vintequatro/trophy-variant.png")), jPanel2); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(254, 254, 254));

        jMenu1.setText("Opções");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Nova atividade");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Editar atividade");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Informações GamesApp");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTRanking)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTRanking, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void jListaAtividadesAndamento1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaAtividadesAndamento1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListaAtividadesAndamento1MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jListaAtividadesAndamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaAtividadesAndamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListaAtividadesAndamentoMouseClicked

    private void jListaTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaTurmasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListaTurmasMouseClicked

    private void jTFPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbCorTurma;
    private javax.swing.JLabel jLbCurso;
    private javax.swing.JLabel jLbData;
    private javax.swing.JLabel jLbData1;
    private javax.swing.JLabel jLbHora;
    private javax.swing.JLabel jLbHora1;
    private javax.swing.JLabel jLbImagemTurma;
    private javax.swing.JLabel jLbLocal;
    private javax.swing.JLabel jLbLocal1;
    private javax.swing.JLabel jLbNomeAtividade;
    private javax.swing.JLabel jLbNomeAtividade1;
    private javax.swing.JLabel jLbNomeTurma;
    private javax.swing.JLabel jLbPontuacaoPrimeiro;
    private javax.swing.JLabel jLbPontuacaoPrimeiro1;
    private javax.swing.JLabel jLbPontuacaoSegundo;
    private javax.swing.JLabel jLbPontuacaoSegundo1;
    private javax.swing.JLabel jLbPontuacaoTerceiro;
    private javax.swing.JLabel jLbPontuacaoTerceiro1;
    private javax.swing.JLabel jLbPontuacaoTotal;
    private javax.swing.JLabel jLbPontuacaoTotal1;
    private javax.swing.JLabel jLbQntAlunos;
    private javax.swing.JList<String> jListaAtividadesAndamento;
    private javax.swing.JList<String> jListaAtividadesAndamento1;
    private javax.swing.JList<String> jListaTurmas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTADescricao;
    private javax.swing.JTextArea jTADescricao1;
    private javax.swing.JTabbedPane jTEmAndamento;
    private javax.swing.JTextField jTFPesquisar;
    private javax.swing.JTabbedPane jTRanking;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
